ready for testing

diff --git a/basejump b/basejump
--- a/basejump
+++ b/basejump
@@ -2,72 +2,55 @@
 
 set -e
 
-echo "This will overwrite your dotfiles for profile, bash, git, vim, zsh in `echo ~`"
-read -p "Are you sure you want to do this? [Y/n] " -n 1 -r; echo
-
-###########
-
-echo "Prezto — Instantly Awesome Zsh"
-echo "https://github.com/sorin-ionescu/prezto"
-echo "---------------------------------------"
-
-cd ~
-mkdir .zsh-old
-mv .z* oh-my* .zsh-old
-
-git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
-
-ln -s .zprezto/runcoms/zlogin .zlogin
-ln -s .zprezto/runcoms/zlogout .zlogout
-ln -s .zprezto/runcoms/zpreztorc .zpreztorc
-ln -s .zprezto/runcoms/zprofile .zprofile
-ln -s .zprezto/runcoms/zshenv .zshenv
-ln -s .zprezto/runcoms/zshrc .zshrc
-
-chsh -s /bin/zsh
-
-###########
-
-echo "close terminal and reopen to use prezto"
-
-if [[ $REPLY =~ ^[Yy]$ ]]
-	echo "=> Checking for required software..."
-    for cli in zsh git; do
-   	if ! type "$cli" > /dev/null 2>&1; then
-      "NOTICE $cli is not installed - trying to install"
-	     sudo apt-get install $cli
-    fi
+function software-check(){
+  echo "=> Checking for required software..."
+    for cli in git rsync zsh; do
+      if ! type "$cli" > /dev/null 2>&1; then
+        "NOTICE $cli is not installed - trying to install"
+	 sudo apt-get install $cli
+      fi
   done
   echo "=> Checing for required packages..."
-  if [ ! -d '/usr/share/doc/vim-nox' ]; then
-    sudo apt-get install vim-nox
-  fi
-then
-	echo -n "=> Creating directories..." 
-  	if [ ! -d "${HOME}/.vim/backups" ]; then
-    		mkdir -p ${HOME}/.vim/backups
-  	fi
-	echo "done"
+    if [ ! -d '/usr/share/doc/vim-nox' ]; then
+      sudo apt-get install vim-nox
+    fi
+}
 
-	echo -n "=> Copying files..." 
-	cp -Rf src/.bashrc src/.gitconfig src/.gitignore src/.gitrc src/.oh-my-zsh src/.profile src/.ssh src/.vim src/.vimrc ${HOME}
-	echo "done"
+function install-dots(){
+  git clone https://github.com/philcryer/dotty.git
+  rsync --exclude ".git/" --exclude "README.md" --exclude "LICENSE" -avh --no-perms . ~;
+}
 
-  	echo -n "=> Installing zpresto for zsh..."
-    chmod 755 src/install_prezto.sh
-  	cd src; ./install_prezto.sh
-	echo "done"
+function install-prezto(){
+	git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
+	ln -s .zprezto/runcoms/zlogin .zlogin
+	ln -s .zprezto/runcoms/zlogout .zlogout
+	ln -s .zprezto/runcoms/zpreztorc .zpreztorc
+	ln -s .zprezto/runcoms/zprofile .zprofile
+	ln -s .zprezto/runcoms/zshenv .zshenv
+	ln -s .zprezto/runcoms/zshrc .zshrc
+}
 
-  	echo "=> Attempting to change shell..."
-  	chsh -s /bin/zsh
-	echo "done"
+if [ "$1" == "--force" -o "$1" == "-f" ]; then
+  software-check;
+  install-dots;
+else
+  read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
+  echo "";
+    if [[ $REPLY =~ ^[Yy]$ ]]; then
+      software-check;
+      install-dots;
+    fi;
+fi;
 
-	echo "NOTICE:"
-	echo "=> ZSHRC check/change timezone, currently set as `cat ~/.zshrc|grep TZ`"
-	echo "=> GITCONFIG change name and eamil"
+if [ ! -d '~/.zprezto' ]; then
+	install-prezto;
+
+	echo;echo "NOTICE: attempting to change your default shell (provide password)"
+	chsh -s /bin/zsh
+
+	echo "NOTICE: exiting shell for changes to be applied"
+	exit 
 fi
-
-exit 0
-
 
 exit 0
